### ISSUE TITLE
При запуске автотеста не удается получить доступ к сайту

### ISSUE THREAD

**Issue by Anechka2019** [Anechka2019/Selenide2_2#1]
## 1. В программе IntelliJ IDEA:
- прописываю зависимости в build.gradle
- создаю файл .gitignore
- добавляю файл appveyor.yml
- добавляю папку artifacts с целевым сервисом app-card-delivery.jar
- создаю в папке test  новый класс java с именем SelenideSecondTest и прописываю код
## 2. Запускаю Git
- запускаю git init
- добавляю все файлы
- добавляю целевой сервис командой git add -f artifacts/app-card-delivery.jar
- делаю коммит
## 3. В программе IntelliJ IDEA:
- запускаю автотесты
- при запуске браузера выходит сообщение:

> Не удается получить доступ к сайтуСайт localhost не позволяет установить соединение.
> Попробуйте сделать следующее:
> 
> Проверьте подключение к Интернету.
> Проверьте настройки прокси-сервера и брандмауэра.
> ERR_CONNECTION_REFUSED_

![readmsg](https://user-images.githubusercontent.com/56668958/69476700-38877380-0dee-11ea-8945-2c7a1a7690a6.png)

- в программе IntelliJ IDEA выходит сообщение:

> 2 tests completed, 2 failed

**Comment by ArRomanov** [comment]
Склонировал ваш репозиторий, запустил файл сервиса командой **java -jar artifacts/app-card-delivery.jar**, запустил тесты командой **./gradlew test**, результат на скриншоте. 

![image](https://user-images.githubusercontent.com/23121947/69480185-2a4d4d80-0e16-11ea-8ac3-fb6abc99cedc.png)

У вас наверняка не запущен сервис, как минимум, я должен посмотреть на логи после запуска jar файла.
